name: Run Gradle check on Pull Requests

on: pull_request

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle check
        run: ./gradlew -Dorg.gradle.jvmargs=-Xmx2g check

